// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Tyrqvir/anti-brute-force/internal/config"
	"github.com/Tyrqvir/anti-brute-force/internal/limiter/lickybucket"
	"github.com/Tyrqvir/anti-brute-force/internal/logger"
	"github.com/Tyrqvir/anti-brute-force/internal/server/grpc"
	"github.com/Tyrqvir/anti-brute-force/internal/storage/redis"
	"github.com/Tyrqvir/anti-brute-force/internal/usercases"
)

// Injectors from wire.go:

func setupWire(config2 *config.Config, logger2 logger.Logger) (*grpc.Server, error) {
	storageRedis := redis.New(config2, logger2)
	limiter := lickybucket.New(storageRedis, logger2)
	antiBruteForceCase := usercases.NewUseCase(limiter, storageRedis)
	server := grpc.New(antiBruteForceCase, logger2, config2)
	return server, nil
}
